import { describe, expect, it } from "vitest";

import type { FsNode } from "@/api/workspace";
import { DERIVED_DIR, isDerivedNode } from "@/lib/workspace";

/**
 * Issue #1222: which notes the pane must refuse to edit.
 *
 * The console used to offer a fully working Edit tab on a file under
 * `derived/` — a file whose own first paragraph reads "Do not edit this file".
 * Typing into it produced a `400` per autosave, a status line promising a retry
 * that could never succeed, and silent loss of the text on navigating away.
 *
 * The rule is a **folder** rule, mirroring `is_derived_path` in
 * `src/ledger/derived.rs`. That module argues why: a per-file list fails open,
 * because a ledger declared next week renders a file no list has heard of. So
 * the cases that matter here are the ones a per-file check would get wrong —
 * an unknown file under the folder, and a deep descendant of it.
 */

function node(partial: Partial<FsNode> & { id: string; name: string }): FsNode {
  return {
    kind: "file",
    parentId: null,
    updatedAt: 0,
    ...partial,
  } as FsNode;
}

const DERIVED = node({ id: "d", name: "derived", kind: "folder" });
const TREE: FsNode[] = [
  DERIVED,
  node({ id: "promises", name: "CUSTOMER_PROMISES.md", parentId: "d" }),
  // A file no ledger currently claims — the stale render a retired ledger
  // leaves behind. The host refuses this one too.
  node({ id: "orphan", name: "QA_THROWAWAY.md", parentId: "d" }),
  node({ id: "sub", name: "archive", kind: "folder", parentId: "d" }),
  node({ id: "deep", name: "OLD_GOALS.md", parentId: "sub" }),
  // An ordinary note, and a folder whose name merely contains the word.
  node({ id: "notes", name: "QA notes", kind: "folder" }),
  node({ id: "perf", name: "Perf budget.md", parentId: "notes" }),
  node({ id: "lookalike", name: "derived-notes", kind: "folder" }),
  node({ id: "inside", name: "Scratch.md", parentId: "lookalike" }),
];

describe("which notes the workspace refuses to edit", () => {
  it("refuses every file under the derived folder", () => {
    expect(isDerivedNode(TREE, "promises")).toBe(true);
    // The whole reason the rule is the folder: no list of ledgers is consulted.
    expect(isDerivedNode(TREE, "orphan")).toBe(true);
    expect(isDerivedNode(TREE, "deep")).toBe(true);
    // The folder itself, which the host's guard also covers.
    expect(isDerivedNode(TREE, "d")).toBe(true);
  });

  it("leaves ordinary notes alone", () => {
    expect(isDerivedNode(TREE, "perf")).toBe(false);
    expect(isDerivedNode(TREE, "notes")).toBe(false);
    // Only the root segment counts, so a folder that merely starts with the
    // word is not swept up — a false positive here takes away an editor an
    // operator is entitled to.
    expect(isDerivedNode(TREE, "inside")).toBe(false);
    expect(isDerivedNode(TREE, "lookalike")).toBe(false);
  });

  it("answers false for nothing open, rather than throwing", () => {
    expect(isDerivedNode(TREE, null)).toBe(false);
    expect(isDerivedNode(TREE, "not-a-node")).toBe(false);
    expect(isDerivedNode([], "promises")).toBe(false);
  });

  it("cannot be stepped around by capitalising a letter", () => {
    // The host's guard is explicitly case-insensitive on the folder segment,
    // and says why: "a guard that can be stepped around by capitalising a
    // letter is not a guard". A console that disagreed would offer an Edit tab
    // for exactly the files the host refuses.
    const shouty: FsNode[] = [
      node({ id: "D", name: "Derived", kind: "folder" }),
      node({ id: "f", name: "GOALS.md", parentId: "D" }),
    ];
    expect(isDerivedNode(shouty, "f")).toBe(true);
  });

  it("names the folder once, so the host can be followed if it moves", () => {
    expect(DERIVED_DIR).toBe("derived");
  });
});
